# File for install the required packages if needed.

if (!require("tm"))
  install.packages("tm")
if (!require("textclean"))
  install.packages("textclean")
if (!require("dplyr"))
  install.packages("dplyr")
if (!require("ggplot2"))
  install.packages("ggplot2")
if (!require("ggwordcloud"))
  install.packages("ggwordcloud")
if (!require("udpipe"))
  install.packages("udpipe")
if (!require("kableExtra"))
  install.packages("kableExtra")
if (!require("sentimentr"))
  install.packages("sentimentr")
if (!require("SentimentAnalysis"))
  install.packages("SentimentAnalysis")
